name: 'Social Post'
author: 'Jo Colina'
description: 'A simple action to create posts on Social Media'

inputs:
  MESSAGE_TEMPLATE:
    description: 'What should be sent? (only text enabled)'
    required: true
    default: 'I published a new release to {{ platform_name }}: v${{ github.ref }}!'

  # #######
  # TWITTER
  # #######
  TWITTER_ENABLED:
    description: 'Should post to twitter?'
    required: true
    default: false

  TWITTER_CONSUMER_KEY:
    description: 'Twitter Consumer Key from your App'
    required: false
    default: ''

  TWITTER_CONSUMER_SECRET:
    description: 'Twitter Consumer Secret from your App'
    required: false
    default: ''

  TWITTER_API_KEY:
    description: 'Twitter API Key from your App'
    required: false
    default: ''

  TWITTER_API_SECRET:
    description: 'Twitter API Secret from your App'
    required: false
    default: ''

  # #######
  # DISCORD
  # #######
  DISCORD_ENABLED:
    description: 'Should post to Discord?'
    required: true
    default: false

  DISCORD_WEBHOOK:
    description: 'Discord webhook to post message'
    required: false
    default: ''

  # #######
  # SLACK
  # #######
  SLACK_ENABLED:
    description: 'Should post to Slack?'
    required: true
    default: false

  SLACK_OAUTH_TOKEN:
    description: 'Slack bot token'
    required: false
    default: ''

  SLACK_BOT_NAME:
    description: 'The username the bot will have when sending the message'
    required: false

  SLACK_CHANNEL:
    description: 'The channel the bot should post to (the # is required)'
    required: false,
    default: '#general'


runs:
  using: 'node12'
  main: 'index.js'

branding:
  icon: activity
  color: blue
